openapi: 3.0.0
info:
  description: "Scan files for viruses, trojans, and other kinds of malware."
  title: attachmentAV
  version: 1.0.0
servers:
- url: https://eu.developer.attachmentav.com/v1
security:
- apiKeyAuth: []
- bearerAuth: []
tags:
- name: attachmentAV
paths:
  /scan/sync/binary:
    post:
      description: "Upload a file, scan the file, and return the scan result."
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScanResult"
          description: Success
      tags:
      - attachmentAV
      x-content-type: application/octet-stream
      x-accepts:
      - application/json
  /scan/sync/download:
    post:
      description: "Download a file from a remote location (HTTP/HTTPS), scan the\
        \ file, and return the scan result."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SyncDownloadScanRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScanResult"
          description: Success
      tags:
      - attachmentAV
      x-content-type: application/json
      x-accepts:
      - application/json
  /scan/sync/s3:
    post:
      description: "Download a file from S3, scan the file, and return the scan result.\
        \ A bucket policy is required to grant attachmentAV access to the S3 objects."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SyncS3ScanRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScanResult"
          description: Success
      tags:
      - attachmentAV
      x-content-type: application/json
      x-accepts:
      - application/json
  /scan/async/download:
    post:
      description: "Download a file from a remote location (HTTP/HTTPS), scan the\
        \ file, and post the scan result to your callback URL."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AsyncDownloadScanRequest"
        required: true
      responses:
        "204":
          description: Success
      tags:
      - attachmentAV
      x-content-type: application/json
      x-accepts:
      - application/json
  /scan/async/s3:
    post:
      description: "Download a file from S3, scan the file, and post the scan result\
        \ to your callback URL. A bucket policy is required to grant attachmentAV\
        \ access to the S3 objects."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AsyncS3ScanRequest"
        required: true
      responses:
        "204":
          description: Success
      tags:
      - attachmentAV
      x-content-type: application/json
      x-accepts:
      - application/json
  /whoami:
    get:
      description: Get information abour yourself.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Whoami"
          description: Success
      tags:
      - attachmentAV
      x-accepts:
      - application/json
components:
  schemas:
    ScanResult:
      example:
        size: size
        realfiletype: realfiletype
        finding: finding
        status: status
      properties:
        status:
          type: string
        finding:
          type: string
        size:
          type: string
        realfiletype:
          type: string
      type: object
    SyncDownloadScanRequest:
      example:
        download_url: download_url
        download_headers:
          key: download_headers
      properties:
        download_url:
          type: string
        download_headers:
          additionalProperties:
            type: string
          type: object
      required:
      - download_url
      type: object
    SyncS3ScanRequest:
      example:
        bucket: bucket
        version: version
        key: key
      properties:
        bucket:
          type: string
        key:
          type: string
        version:
          type: string
      required:
      - bucket
      - key
      type: object
    AsyncDownloadScanRequest:
      example:
        callback_url: callback_url
        trace_id: trace_id
        download_url: download_url
        callback_headers:
          key: callback_headers
        download_headers:
          key: download_headers
        custom_data: custom_data
      properties:
        download_url:
          type: string
        download_headers:
          additionalProperties:
            type: string
          type: object
        callback_url:
          type: string
        callback_headers:
          additionalProperties:
            type: string
          type: object
        trace_id:
          type: string
        custom_data:
          type: string
      required:
      - callback_url
      - download_url
      type: object
    AsyncS3ScanRequest:
      example:
        bucket: bucket
        callback_url: callback_url
        trace_id: trace_id
        callback_headers:
          key: callback_headers
        version: version
        custom_data: custom_data
        key: key
      properties:
        bucket:
          type: string
        key:
          type: string
        version:
          type: string
        callback_url:
          type: string
        callback_headers:
          additionalProperties:
            type: string
          type: object
        trace_id:
          type: string
        custom_data:
          type: string
      required:
      - bucket
      - callback_url
      - key
      type: object
    Whoami:
      example:
        tenantId: tenantId
      properties:
        tenantId:
          type: string
      type: object
  securitySchemes:
    apiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey
    bearerAuth:
      scheme: bearer
      type: http

